# Generated by Django 5.0.2 on 2024-02-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(),
        ),
    ]
