# Generated by Django 5.0.2 on 2024-02-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_faculty_studyyear_course_faculty_course_study_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyyear',
            name='semester',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='year',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
