# Generated by Django 5.0.2 on 2024-02-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_studyyear_semester_alter_studyyear_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyyear',
            name='semester',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
