# Generated by Django 5.0.2 on 2024-03-15 13:20

import courses.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_content_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'الكلية', 'verbose_name_plural': 'الكليات'},
        ),
        migrations.AlterModelOptions(
            name='studyyear',
            options={'verbose_name': 'السنة الدراسية', 'verbose_name_plural': 'السنوات الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name': 'المادة', 'verbose_name_plural': 'المواد'},
        ),
        migrations.AddField(
            model_name='course',
            name='is_exam_active',
            field=models.BooleanField(default=False, verbose_name='هل الامتحان نشط؟'),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.faculty', verbose_name='الكلية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=courses.models.file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'pdf', 'docx', 'pptx', 'xls'])], verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=courses.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='semester',
            field=models.CharField(max_length=50, verbose_name='الفصل'),
        ),
        migrations.AlterField(
            model_name='studyyear',
            name='year',
            field=models.CharField(max_length=50, verbose_name='السنة'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
    ]
