# Generated by Django 5.0.2 on 2024-03-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_faculty_options_alter_studyyear_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
    ]
