# Generated by Django 5.0.2 on 2024-02-28 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='study_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.studyyear'),
            preserve_default=False,
        ),
    ]
