# Generated by Django 5.0.2 on 2024-03-01 15:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_active'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='document',
        #    name='document',
        #    field=models.FileField(upload_to=accounts.models.user_directory_path),
        #),
    ]
