# Generated by Django 5.0.2 on 2024-03-15 13:20

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_profile_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='الصورة الشخصية'),
        ),
        #migrations.AlterField(
        #    model_name='document',
        #    name='document',
        #    field=models.FileField(upload_to=accounts.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'pdf', 'docx', 'pptx', 'xls'])], verbose_name='المستند'),
        #),
    ]
