# Generated by Django 5.0.2 on 2024-03-20 00:33

import accounts.models
import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_photo_alter_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate_photo',
            field=models.ImageField(default=1, upload_to=accounts.models.student_certificate_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='الشهادة الثانوية أو إجازة في القرآن الكريم أو شهادة شرعية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='country_born',
            field=django_countries.fields.CountryField(default=1, max_length=2, verbose_name='بلد الميلاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='country_of_residence',
            field=django_countries.fields.CountryField(default=1, max_length=2, verbose_name='بلد الإقامة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default=1, max_length=100, verbose_name='اسم الأب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id_photo',
            field=models.ImageField(default=1, upload_to=accounts.models.student_certificate_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='صورة إثبات الشخصية (جواز السفر أو بطاقة الهوية أو قيد مدني)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(default=1, max_length=50, verbose_name='اللغة الأم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=1, max_length=25, verbose_name='رقم الموبايل مع الرمز الدولي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(choices=[('شهادة ثانوية أو ما يعادلها من المعاهد الشرعية', 'شهادة ثانوية أو ما يعادلها من المعاهد الشرعية'), ('إجازة بالقرآن الكريم', 'إجازة بالقرآن الكريم'), ('شهادة أكاديمية الإمام الأعظم أبي حنيفة النعمان رضي الله تعالى عنه', 'شهادة أكاديمية الإمام الأعظم أبي حنيفة النعمان رضي الله تعالى عنه'), ('بكالوريوس', 'بكالوريوس'), ('ماجستير', 'ماجستير'), ('دكتوراة', 'دكتوراة')], default=1, max_length=100, verbose_name='المؤهل العلمي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(upload_to=accounts.models.user_profile_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='الصورة الشخصية'),
        ),
    ]
