# Generated by Django 5.0.2 on 2024-03-10 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_updated'),
        ('exams', '0002_examquestion_examchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('student_email', models.EmailField(max_length=254)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_tokens', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examquestion')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examchoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
