# Generated by Django 5.0.2 on 2024-03-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examtoken_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
    ]
