# Generated by Django 5.0.2 on 2024-03-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_emails_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='mark',
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(default=0, help_text='Total marks for the exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examquestion',
            name='mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marks for this choice', max_digits=6),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='mark_obtained',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marks obtained for this question', max_digits=6),
        ),
    ]
