# Generated by Django 5.0.2 on 2024-03-15 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_options_alter_document_options_and_more'),
        ('courses', '0013_alter_content_options_alter_file_options_and_more'),
        ('exams', '0006_studentanswer_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'الخيار', 'verbose_name_plural': 'الخيارات'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'امتحان', 'verbose_name_plural': 'الامتحانات'},
        ),
        migrations.AlterModelOptions(
            name='examtoken',
            options={'verbose_name': 'رمز الامتحان', 'verbose_name_plural': 'رموز الامتحانات'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'السؤال', 'verbose_name_plural': 'الأسئلة'},
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={'verbose_name': 'بنك الأسئلة', 'verbose_name_plural': 'بنوك الأسئلة'},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'verbose_name': 'إجابة الطالب', 'verbose_name_plural': 'إجابات الطلاب'},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='المدة بالدقائق'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='نص الخيار'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='صحيح'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='emails_sent',
            field=models.BooleanField(default=False, verbose_name='تم إرسال البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='modules',
            field=models.ManyToManyField(related_name='exams', to='courses.module', verbose_name='الوحدات'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='number_of_questions',
            field=models.PositiveIntegerField(verbose_name='عدد الأسئلة'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='scheduled_datetime',
            field=models.DateTimeField(verbose_name='التاريخ والوقت المجدول للامتحان'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(verbose_name='العلامة الإجمالية'),
        ),
        migrations.AlterField(
            model_name='examchoice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='نص الخيار'),
        ),
        migrations.AlterField(
            model_name='examchoice',
            name='exam_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_choices', to='exams.examquestion', verbose_name='سؤال الامتحان'),
        ),
        migrations.AlterField(
            model_name='examchoice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='صحيح'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam', verbose_name='الامتحان'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='العلامة'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='examtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='examtoken',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_tokens', to='exams.exam', verbose_name='الامتحان'),
        ),
        migrations.AlterField(
            model_name='examtoken',
            name='student_email',
            field=models.EmailField(max_length=254, verbose_name='بريد الطالب'),
        ),
        migrations.AlterField(
            model_name='examtoken',
            name='token',
            field=models.CharField(max_length=100, unique=True, verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='examtoken',
            name='used',
            field=models.BooleanField(default=False, verbose_name='تم الاستخدام'),
        ),
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.module', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.questionbank', verbose_name='مصرف الأسئلة'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.instructor', verbose_name='المالك'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='الامتحان'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='exam_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examquestion', verbose_name='سؤال الامتحان'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='mark_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='العلامات المحصلة لهذا السؤال'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examchoice', verbose_name='الخيار المحدد'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='الطالب'),
        ),
    ]
