# Generated by Django 5.0.2 on 2024-03-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_choice_options_alter_exam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='lock_course_during_exam',
            field=models.BooleanField(default=False, verbose_name='قفل الدروس خلال الامتحان'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(verbose_name='العلامة'),
        ),
    ]
